#!/usr/bin/env bash
set -euo pipefail

DATA_ROOT="${1:-/srv/telehub/captcha-lab}"
MOUNT_ROOT="${CAPTCHA_LAB_MOUNT_ROOT:-/srv/telehub}"

if ! command -v findmnt >/dev/null 2>&1; then
  echo "ERROR: findmnt is required to verify the target filesystem." >&2
  exit 2
fi

if [ ! -d "$MOUNT_ROOT" ]; then
  echo "ERROR: expected external mount is not visible: $MOUNT_ROOT" >&2
  echo "Expose/mount the data volume first; refusing to fall back to the OS disk." >&2
  exit 3
fi

ROOT_SOURCE="$(findmnt -n -o SOURCE -T /)"
DATA_SOURCE="$(findmnt -n -o SOURCE -T "$MOUNT_ROOT")"
ROOT_FSTYPE="$(findmnt -n -o FSTYPE -T /)"
DATA_FSTYPE="$(findmnt -n -o FSTYPE -T "$MOUNT_ROOT")"

if [ -z "$ROOT_SOURCE" ] || [ -z "$DATA_SOURCE" ]; then
  echo "ERROR: could not resolve filesystem sources." >&2
  exit 4
fi

if [ "$ROOT_SOURCE" = "$DATA_SOURCE" ]; then
  echo "ERROR: $MOUNT_ROOT resolves to the OS/root filesystem ($ROOT_SOURCE)." >&2
  echo "Refusing to create CAPTCHA Lab data there." >&2
  exit 5
fi

mkdir -p \
  "$DATA_ROOT/repos" \
  "$DATA_ROOT/models" \
  "$DATA_ROOT/cache/playwright" \
  "$DATA_ROOT/cache/huggingface" \
  "$DATA_ROOT/cache/pip" \
  "$DATA_ROOT/artifacts" \
  "$DATA_ROOT/tmp"

ENV_FILE="$DATA_ROOT/env.sh"
cat > "$ENV_FILE" <<EOF
# Generated by tools/setup_data_root.sh
export CAPTCHA_LAB_DATA_ROOT="$DATA_ROOT"
export CAPTCHA_LAB_ARTIFACTS="$DATA_ROOT/artifacts"
export CAPTCHA_LAB_TMPDIR="$DATA_ROOT/tmp"
export PLAYWRIGHT_BROWSERS_PATH="$DATA_ROOT/cache/playwright"
export HF_HOME="$DATA_ROOT/cache/huggingface"
export PIP_CACHE_DIR="$DATA_ROOT/cache/pip"
export TMPDIR="$DATA_ROOT/tmp"
EOF

chmod 600 "$ENV_FILE"

echo "CAPTCHA Lab external storage is ready."
echo "  OS/root : $ROOT_SOURCE ($ROOT_FSTYPE)"
echo "  data    : $DATA_SOURCE ($DATA_FSTYPE)"
echo "  root    : $DATA_ROOT"
echo "  env     : $ENV_FILE"
echo "  free    : $(df -h "$MOUNT_ROOT" | awk 'NR==2 {print $4}')"
echo
echo "Use: source '$ENV_FILE'"
